name: lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code Quality Checks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node Dependencies
        run: npm ci

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Check PHP Code Style
        run: vendor/bin/pint --test

      - name: Run PHPStan
        run: composer phpstan

      - name: Check TypeScript Types
        run: npm run types

      - name: Lint Frontend Code
        run: npm run lint

      - name: Check Frontend Format
        run: npm run format:check
